//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการตามที่ขอเรียบร้อยแล้วค่ะ....
        /// </summary>
        internal static string ActionSuccess {
            get {
                return ResourceManager.GetString("ActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and Developed by Neo-Net Soft Co., Ltd. (Best view with IE8+/FF3+, Screen resolution: 1280x768 or more, Text size: Medium).
        /// </summary>
        internal static string CopyrightDef2 {
            get {
                return ResourceManager.GetString("CopyrightDef2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy;2010-2011 &lt;a href=&apos;http://www.neo-netsoft.com&apos; target=&apos;_blank&apos;&gt;Neo-Net Soft Co., Ltd.&lt;/a&gt;.
        /// </summary>
        internal static string CopyrightString {
            get {
                return ResourceManager.GetString("CopyrightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลเรียบร้อยแล้วค่ะ....
        /// </summary>
        internal static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แน่ใจว่าต้องการปิดหน้าจอโดยไม่บันทึกข้อมูล ?.
        /// </summary>
        internal static string JS_Alert_ConfirmExitWithoutSave {
            get {
                return ResourceManager.GetString("JS_Alert_ConfirmExitWithoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาบันทึกการแก้ไขรายละเอียดให้เรียบร้อยก่อนนะคะ.
        /// </summary>
        internal static string JS_Alert_NotEdittingDetail {
            get {
                return ResourceManager.GetString("JS_Alert_NotEdittingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบข้อมูล กรุณากรอกให้ถูกต้องคะ.
        /// </summary>
        internal static string JS_Alert_NotFoundData {
            get {
                return ResourceManager.GetString("JS_Alert_NotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ต้องการลบรายการที่เลือกหรือไม่ ?.
        /// </summary>
        internal static string JS_ConfirmGiveUp {
            get {
                return ResourceManager.GetString("JS_ConfirmGiveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถกระทำการตามที่สั่งได้ เนื่องจากหาข้อมูลตามที่ระบุไม่พบค่ะ.
        /// </summary>
        internal static string NotFoundData {
            get {
                return ResourceManager.GetString("NotFoundData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาบันทึกข้อมูลรายละเอียดก่อนกดปุ่ม Save.
        /// </summary>
        internal static string RV_DetailEditing {
            get {
                return ResourceManager.GetString("RV_DetailEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่มีสิทธิในการแก้ไข/บันทึกข้อมูล กรุณากดยกเลิก (X) เพื่อปิดหน้าจอนี้.
        /// </summary>
        internal static string RV_UserCannotEdit {
            get {
                return ResourceManager.GetString("RV_UserCannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่สามารถบันทึกข้อมูล (กรุณาดูรายละเอียดในแต่ละช่อง):.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลเรียบร้อยแล้วค่ะ....
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลที่ส่งมาในช่อง Address ไม่ถูกต้อง กรุณาอย่าพิมพ์ในช่อง Address เอง.
        /// </summary>
        internal static string StdReference_QueryStringMismatch {
            get {
                return ResourceManager.GetString("StdReference_QueryStringMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samutsakhon Immigration Office.
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
    }
}
